In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)
print(arr.shape)


[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [3]:
newArr = arr.reshape(2, 5)
print(newArr)
print(newArr.shape)
print(newArr.dtype.name)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
int64


In [4]:
zeroArray = np.zeros((3, 4))
print(zeroArray)
zeroArray = np.zeros((3, 4), dtype=np.int16)
print(zeroArray)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
zeroArray[ 0, 0 ] = 1
print(zeroArray)

[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [6]:
oneArray = np.ones((2, 3))
print(oneArray)
emptyArray = np.empty((2, 3))
print(emptyArray)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arr = np.arange(10, 30, 2)
print(arr)
arr = arr.reshape(2, 5)
print(arr)

[10 12 14 16 18 20 22 24 26 28]
[[10 12 14 16 18]
 [20 22 24 26 28]]


In [8]:
arr = np.linspace(0, 2, 9)
print(arr)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [9]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(b)
print(a - b)
print(a + b)
print(a * b)
print(a ** b)

[0 1 2 3]
[20 29 38 47]
[20 31 42 53]
[  0  30  80 150]
[     1     30   1600 125000]


In [10]:
a=np.array([[1,1],[0,1]])
b=c=a
print(a)
print(b)
print(c)

b[0][0] = 100
print(a)
print(b)
print(c)

[[1 1]
 [0 1]]
[[1 1]
 [0 1]]
[[1 1]
 [0 1]]
[[100   1]
 [  0   1]]
[[100   1]
 [  0   1]]
[[100   1]
 [  0   1]]


In [11]:
d=a.copy()
a[0][0] = 1
print(a)
print(d)



[[1 1]
 [0 1]]
[[100   1]
 [  0   1]]


In [12]:
a= np.array([1,2,3,4])
print(a)
print(a[0:2])
print(a[2:])
print(a[:2])
print(a[-2:])
print(a[-2:-1])
print(a[::-1])


[1 2 3 4]
[1 2]
[3 4]
[1 2]
[3 4]
[3]
[4 3 2 1]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
arr = arr.ravel()
print(arr)
arr = arr.reshape(3, 3)
print(arr)
arr = arr.T
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
